### ISSUE TITLE
Which version to use?

### ISSUE THREAD

**Issue by KarinSchork** [HSU-HPC/HarmonizR#1]
Hello!

I wanted to try out HarmonizR and I am confused which version to use.

https://github.com/SimonSchlumbohm/HarmonizR seems to be the "old" one from the publication? I already tested it but there seem to be some improvements in this repo here.

And there are also separate repos for version 1.0 and 1.1?

Which one would you recommend to use?

Best regards
Karin

**Comment by SimonSchlumbohm** [comment]
Dear Karin Schork,

apologies for the late answer, as I have not been automatically notified for some reason. The structure on GitHub has been reworked for HarmonizR; under 
https://github.com/HSU-HPC/HarmonizR 
you will be able to find all versions with the latest release being the most up-to-date version. As this package is part of active research, versions have been changing a bunch, but I hope you are able to use the package fine.

(The link you posted here is indeed the original Nature Communications release-version of the package, which is always provided via a stable GitHub link.)

With best regards

Simon Schlumbohm

**Comment by KarinSchork** [comment]
Dear Simon,

thanks! I will check it out!

Best regards
Karin
